name: 'Deploy SER script: `email_summary.R`'
'on':
  schedule:
    - cron:  '30 4 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: 'Deploy script: `email_summary.R`'
        env:
          DRIVE_AUTH_TOKEN_PATH: $
          GMAILR_APP: $
          SER_ACCESS_SECRET: $
          SER_ACCESS_TOKEN: $
          SER_CONSUMER_KEY: $
          SER_CONSUMER_SECRET: $
        run: |-
          Rscript -e "library(ser); source_ser('email_summary')"
    container: rocker/verse:latest
